# =============================================================================
# CONFIGURATION COOLIFY - Station Traffeyère IoT/AI Platform
# Déploiement sur https://coolify.ccdigital.fr
# Repository: https://github.com/bandidood/convergence-iot-ai-platform.git
# Projet RNCP 39394 - Expert en Systèmes d'Information et Sécurité
# =============================================================================

# Informations du projet
name: station-traffeyere-iot-platform
description: "Plateforme IoT/AI Station Traffeyère avec backend FastAPI et frontend Next.js - RNCP 39394"
environment: production

# =============================================================================
# SERVICES À DÉPLOYER VIA COOLIFY
# =============================================================================

services:
  # Base de données PostgreSQL
  postgres:
    type: postgresql
    image: postgres:15-alpine
    name: postgres-traffeyere
    environment:
      POSTGRES_DB: station_traffeyere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    memory: 512
    cpu: 0.5
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d station_traffeyere"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Cache Redis
  redis:
    type: redis
    image: redis:7-alpine
    name: redis-traffeyere
    command: "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes"
    volumes:
      - redis_data:/data
    memory: 256
    cpu: 0.25
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  # Base de données temporelle InfluxDB
  influxdb:
    type: service
    image: influxdb:2.7-alpine
    name: influxdb-traffeyere
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: traffeyere
      DOCKER_INFLUXDB_INIT_BUCKET: iot_sensors
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_ADMIN_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    memory: 512
    cpu: 0.5
    domains:
      - "influx.traffeyere.ccdigital.fr"
    ports:
      - "8086:8086"

  # Message Broker MQTT
  mosquitto:
    type: service
    image: eclipse-mosquitto:2.0
    name: mosquitto-traffeyere
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/mosquitto/pwfile:/mosquitto/config/pwfile
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    memory: 128
    cpu: 0.25
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket
    domains:
      - "mqtt.traffeyere.ccdigital.fr"

  # Backend FastAPI
  backend:
    type: application
    source:
      type: git
      repository: https://github.com/bandidood/convergence-iot-ai-platform.git
      branch: master
      dockerfile: ./backend/Dockerfile
    name: backend-traffeyere
    build_command: "docker build -f backend/Dockerfile -t backend-traffeyere ."
    environment:
      # Projet RNCP 39394 - Expert en Systèmes d'Information et Sécurité
      PROJECT_NAME: "Station Traffeyère IoT/AI Platform"
      PROJECT_VERSION: "1.0.0"
      RNCP_CODE: "39394"
      
      # Base de données
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/station_traffeyere
      
      # Redis
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # InfluxDB
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_ADMIN_TOKEN}
      INFLUX_ORG: traffeyere
      INFLUX_BUCKET: iot_sensors
      
      # Application
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: production
      DEBUG: "false"
      
      # MQTT
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_USERNAME: iot_user
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      
      # API IA
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      
      # Configuration métier
      STATION_ID: TRAFFEYERE_001
      STATION_NAME: "Station Traffeyère"
      STATION_LOCATION: "45.764043,4.835659"
      
      # Seuils alertes IoT
      TEMP_ALERT_THRESHOLD: "35.0"
      PRESSURE_ALERT_THRESHOLD: "2.5"
      PH_ALERT_THRESHOLD_MIN: "6.0"
      PH_ALERT_THRESHOLD_MAX: "8.5"
      
      # Paramètres IA
      AI_CONFIDENCE_THRESHOLD: "0.85"
      ANOMALY_DETECTION_WINDOW: "3600"
      MODEL_UPDATE_INTERVAL: "86400"
    volumes:
      - backend_logs:/app/logs
      - backend_models:/app/models
      - backend_uploads:/app/uploads
    memory: 1024
    cpu: 1.0
    domains:
      - "api.traffeyere.ccdigital.fr"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Next.js
  frontend:
    type: application
    source:
      type: git
      repository: https://github.com/bandidood/convergence-iot-ai-platform.git
      branch: master
      dockerfile: ./frontend/Dockerfile
    name: frontend-traffeyere
    build_command: "docker build -f frontend/Dockerfile --build-arg NEXT_PUBLIC_API_URL=https://api.traffeyere.ccdigital.fr -t frontend-traffeyere ."
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.traffeyere.ccdigital.fr
      NEXT_PUBLIC_WS_URL: wss://ws.traffeyere.ccdigital.fr
      NEXT_PUBLIC_MQTT_WS_URL: wss://mqtt.traffeyere.ccdigital.fr
      NEXT_PUBLIC_ENVIRONMENT: production
      
      # Branding projet RNCP
      NEXT_PUBLIC_PROJECT_NAME: "Station Traffeyère IoT/AI Platform"
      NEXT_PUBLIC_RNCP_CODE: "39394"
      NEXT_PUBLIC_VERSION: "1.0.0"
    memory: 512
    cpu: 0.5
    domains:
      - "traffeyere.ccdigital.fr"
      - "www.traffeyere.ccdigital.fr"
      - "app.traffeyere.ccdigital.fr"
    ports:
      - "3000:3000"

  # Monitoring Prometheus
  prometheus:
    type: service
    image: prom/prometheus:latest
    name: prometheus-traffeyere
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://metrics.traffeyere.ccdigital.fr'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    memory: 256
    cpu: 0.25
    domains:
      - "metrics.traffeyere.ccdigital.fr"
    ports:
      - "9090:9090"

  # Monitoring Grafana
  grafana:
    type: service
    image: grafana/grafana:latest
    name: grafana-traffeyere
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: grafana.traffeyere.ccdigital.fr
      GF_SERVER_ROOT_URL: https://grafana.traffeyere.ccdigital.fr
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: ${GRAFANA_DB_PASSWORD}
      
      # Branding personnalisé
      GF_BRANDING_TITLE: "Station Traffeyère Monitoring"
      GF_BRANDING_FOOTER_LINKS: '[{"text": "RNCP 39394", "url": "https://traffeyere.ccdigital.fr"}]'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    memory: 256
    cpu: 0.25
    domains:
      - "grafana.traffeyere.ccdigital.fr"
    ports:
      - "3001:3000"

# =============================================================================
# CONFIGURATION RÉSEAU ET VOLUMES
# =============================================================================

volumes:
  postgres_data: {}
  redis_data: {}
  influxdb_data: {}
  influxdb_config: {}
  mosquitto_data: {}
  mosquitto_logs: {}
  backend_logs: {}
  backend_models: {}
  backend_uploads: {}
  prometheus_data: {}
  grafana_data: {}

# =============================================================================
# CONFIGURATION SSL ET DOMAINES
# =============================================================================

domains:
  main: traffeyere.ccdigital.fr
  api: api.traffeyere.ccdigital.fr
  app: app.traffeyere.ccdigital.fr
  grafana: grafana.traffeyere.ccdigital.fr
  metrics: metrics.traffeyere.ccdigital.fr
  mqtt: mqtt.traffeyere.ccdigital.fr
  influx: influx.traffeyere.ccdigital.fr

ssl:
  enabled: true
  provider: letsencrypt
  email: admin@ccdigital.fr

# =============================================================================
# ORDRE DE DÉPLOIEMENT
# =============================================================================

deploy_order:
  1: [postgres, redis, influxdb]
  2: [mosquitto]
  3: [backend]
  4: [frontend]
  5: [prometheus, grafana]

# =============================================================================
# CONFIGURATION DE SAUVEGARDE
# =============================================================================

backup:
  enabled: true
  schedule: "0 2 * * *"  # Tous les jours à 2h du matin
  retention: 7  # 7 jours
  targets:
    - postgres_data
    - influxdb_data
    - grafana_data
    - backend_models

# =============================================================================
# CONFIGURATION MONITORING ET ALERTES
# =============================================================================

monitoring:
  health_checks:
    enabled: true
    interval: "30s"
    timeout: "10s"
    retries: 3
  
  alerts:
    email: admin@ccdigital.fr
    webhooks:
      - url: "https://api.traffeyere.ccdigital.fr/webhooks/alerts"
        events: ["deployment_failed", "service_unhealthy"]

# =============================================================================
# MÉTADONNÉES PROJET RNCP 39394
# =============================================================================

project:
  type: "RNCP_39394"
  title: "Expert en Systèmes d'Information et Sécurité"
  description: "Plateforme IoT/AI convergente pour transformation digitale des infrastructures critiques"
  technologies:
    - "FastAPI (Python 3.11)"
    - "Next.js (React 18)"
    - "PostgreSQL 15"
    - "Redis 7"
    - "InfluxDB 2.7"
    - "Eclipse Mosquitto 2.0"
    - "Prometheus & Grafana"
    - "Docker & Kubernetes"
  
  competencies:
    - "Architecture de systèmes distribués"
    - "Sécurité des systèmes d'information"
    - "IoT et Edge Computing"
    - "Intelligence artificielle appliquée"
    - "DevSecOps et CI/CD"
    - "Monitoring et observabilité"
  
  contact:
    author: "Johann Lebel"
    email: "johann@ccdigital.fr"
    organization: "CCDigital"
    website: "https://coolify.ccdigital.fr"