version: '3.8'

# ============================================================================
# BLOCKCHAIN LAYER - Station Traffeyère IoT/AI Platform
# Hyperledger Fabric Network pour traçabilité des données
# ============================================================================

services:
  # ===========================================================================
  # ORDERER SERVICES - RAFT Consensus
  # ===========================================================================
  
  # Orderer 0 - Leader
  orderer0.traffeyere.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: traffeyere-orderer0
    restart: unless-stopped
    environment:
      # Configuration générale
      FABRIC_LOGGING_SPEC: INFO
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
      ORDERER_GENERAL_LISTENPORT: 7050
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
      
      # Configuration TLS
      ORDERER_GENERAL_TLS_ENABLED: true
      ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_CLUSTER_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      
      # Configuration Bootstrap
      ORDERER_GENERAL_BOOTSTRAPMETHOD: none
      ORDERER_CHANNELPARTICIPATION_ENABLED: true
      ORDERER_ADMIN_TLS_ENABLED: true
      ORDERER_ADMIN_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_ADMIN_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_ADMIN_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_ADMIN_TLS_CLIENTROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_ADMIN_LISTENADDRESS: 0.0.0.0:7053
      ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:9443
      ORDERER_METRICS_PROVIDER: prometheus
    volumes:
      - orderer0_data:/var/hyperledger/production/orderer
      - ../blockchain-hyperledger/network-config/organizations/ordererOrganizations/traffeyere.com/orderers/orderer0.traffeyere.com/msp:/var/hyperledger/orderer/msp
      - ../blockchain-hyperledger/network-config/organizations/ordererOrganizations/traffeyere.com/orderers/orderer0.traffeyere.com/tls:/var/hyperledger/orderer/tls
    ports:
      - "7050:7050"
      - "7053:7053"
      - "9443:9443"
    networks:
      - traffeyere-blockchain
      - monitoring-network

  # Orderer 1 - Follower
  orderer1.traffeyere.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: traffeyere-orderer1
    restart: unless-stopped
    environment:
      FABRIC_LOGGING_SPEC: INFO
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
      ORDERER_GENERAL_LISTENPORT: 8050
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
      ORDERER_GENERAL_TLS_ENABLED: true
      ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_CLUSTER_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_GENERAL_BOOTSTRAPMETHOD: none
      ORDERER_CHANNELPARTICIPATION_ENABLED: true
      ORDERER_ADMIN_TLS_ENABLED: true
      ORDERER_ADMIN_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_ADMIN_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_ADMIN_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_ADMIN_TLS_CLIENTROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_ADMIN_LISTENADDRESS: 0.0.0.0:8053
      ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:9444
      ORDERER_METRICS_PROVIDER: prometheus
    volumes:
      - orderer1_data:/var/hyperledger/production/orderer
      - ../blockchain-hyperledger/network-config/organizations/ordererOrganizations/traffeyere.com/orderers/orderer1.traffeyere.com/msp:/var/hyperledger/orderer/msp
      - ../blockchain-hyperledger/network-config/organizations/ordererOrganizations/traffeyere.com/orderers/orderer1.traffeyere.com/tls:/var/hyperledger/orderer/tls
    ports:
      - "8050:8050"
      - "8053:8053"
      - "9444:9444"
    networks:
      - traffeyere-blockchain
      - monitoring-network

  # Orderer 2 - Follower
  orderer2.traffeyere.com:
    image: hyperledger/fabric-orderer:2.5
    container_name: traffeyere-orderer2
    restart: unless-stopped
    environment:
      FABRIC_LOGGING_SPEC: INFO
      ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
      ORDERER_GENERAL_LISTENPORT: 9050
      ORDERER_GENERAL_LOCALMSPID: OrdererMSP
      ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/orderer/msp
      ORDERER_GENERAL_TLS_ENABLED: true
      ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_GENERAL_CLUSTER_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_GENERAL_BOOTSTRAPMETHOD: none
      ORDERER_CHANNELPARTICIPATION_ENABLED: true
      ORDERER_ADMIN_TLS_ENABLED: true
      ORDERER_ADMIN_TLS_CERTIFICATE: /var/hyperledger/orderer/tls/server.crt
      ORDERER_ADMIN_TLS_PRIVATEKEY: /var/hyperledger/orderer/tls/server.key
      ORDERER_ADMIN_TLS_ROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_ADMIN_TLS_CLIENTROOTCAS: '[/var/hyperledger/orderer/tls/ca.crt]'
      ORDERER_ADMIN_LISTENADDRESS: 0.0.0.0:9053
      ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:9445
      ORDERER_METRICS_PROVIDER: prometheus
    volumes:
      - orderer2_data:/var/hyperledger/production/orderer
      - ../blockchain-hyperledger/network-config/organizations/ordererOrganizations/traffeyere.com/orderers/orderer2.traffeyere.com/msp:/var/hyperledger/orderer/msp
      - ../blockchain-hyperledger/network-config/organizations/ordererOrganizations/traffeyere.com/orderers/orderer2.traffeyere.com/tls:/var/hyperledger/orderer/tls
    ports:
      - "9050:9050"
      - "9053:9053"
      - "9445:9445"
    networks:
      - traffeyere-blockchain
      - monitoring-network

  # ===========================================================================
  # PEER ORGANIZATION - SAUR (Opérateur)
  # ===========================================================================
  
  # CouchDB pour Peer0 SAUR
  couchdb0-saur:
    image: couchdb:3.3
    container_name: traffeyere-couchdb0-saur
    restart: unless-stopped
    environment:
      COUCHDB_USER: couchdb
      COUCHDB_PASSWORD: adminpass
    volumes:
      - couchdb0_saur_data:/opt/couchdb/data
    ports:
      - "5984:5984"
    networks:
      - traffeyere-blockchain

  # Peer0 SAUR
  peer0.saur.traffeyere.com:
    image: hyperledger/fabric-peer:2.5
    container_name: traffeyere-peer0-saur
    restart: unless-stopped
    environment:
      # Configuration générale
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: traffeyere-blockchain
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_TLS_ENABLED: true
      CORE_PEER_PROFILE_ENABLED: false
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      
      # Configuration Peer
      CORE_PEER_ID: peer0.saur.traffeyere.com
      CORE_PEER_ADDRESS: peer0.saur.traffeyere.com:7051
      CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
      CORE_PEER_CHAINCODEADDRESS: peer0.saur.traffeyere.com:7052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.saur.traffeyere.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.saur.traffeyere.com:7051
      CORE_PEER_LOCALMSPID: SAURMSP
      
      # Configuration CouchDB
      CORE_LEDGER_STATE_STATEDATABASE: CouchDB
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: couchdb0-saur:5984
      CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: couchdb
      CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpass
      
      # Configuration Operations
      CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9446
      CORE_METRICS_PROVIDER: prometheus
    volumes:
      - peer0_saur_data:/var/hyperledger/production
      - ../blockchain-hyperledger/network-config/organizations/peerOrganizations/saur.traffeyere.com/peers/peer0.saur.traffeyere.com/msp:/etc/hyperledger/fabric/msp
      - ../blockchain-hyperledger/network-config/organizations/peerOrganizations/saur.traffeyere.com/peers/peer0.saur.traffeyere.com/tls:/etc/hyperledger/fabric/tls
      - /var/run:/host/var/run
    ports:
      - "7051:7051"
      - "9446:9446"
    networks:
      - traffeyere-blockchain
      - monitoring-network
    external_links:
      - couchdb0-saur

  # ===========================================================================
  # PEER ORGANIZATION - REGULATOR (Régulateur)
  # ===========================================================================
  
  # CouchDB pour Peer0 Regulator
  couchdb0-regulator:
    image: couchdb:3.3
    container_name: traffeyere-couchdb0-regulator
    restart: unless-stopped
    environment:
      COUCHDB_USER: couchdb
      COUCHDB_PASSWORD: adminpass
    volumes:
      - couchdb0_regulator_data:/opt/couchdb/data
    ports:
      - "6984:5984"
    networks:
      - traffeyere-blockchain

  # Peer0 Regulator
  peer0.regulator.traffeyere.com:
    image: hyperledger/fabric-peer:2.5
    container_name: traffeyere-peer0-regulator
    restart: unless-stopped
    environment:
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: traffeyere-blockchain
      FABRIC_LOGGING_SPEC: INFO
      CORE_PEER_TLS_ENABLED: true
      CORE_PEER_PROFILE_ENABLED: false
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/fabric/tls/ca.crt
      CORE_PEER_ID: peer0.regulator.traffeyere.com
      CORE_PEER_ADDRESS: peer0.regulator.traffeyere.com:9051
      CORE_PEER_LISTENADDRESS: 0.0.0.0:9051
      CORE_PEER_CHAINCODEADDRESS: peer0.regulator.traffeyere.com:9052
      CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:9052
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: peer0.regulator.traffeyere.com:9051
      CORE_PEER_GOSSIP_BOOTSTRAP: peer0.regulator.traffeyere.com:9051
      CORE_PEER_LOCALMSPID: RegulatorMSP
      CORE_LEDGER_STATE_STATEDATABASE: CouchDB
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: couchdb0-regulator:5984
      CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: couchdb
      CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpass
      CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9447
      CORE_METRICS_PROVIDER: prometheus
    volumes:
      - peer0_regulator_data:/var/hyperledger/production
      - ../blockchain-hyperledger/network-config/organizations/peerOrganizations/regulator.traffeyere.com/peers/peer0.regulator.traffeyere.com/msp:/etc/hyperledger/fabric/msp
      - ../blockchain-hyperledger/network-config/organizations/peerOrganizations/regulator.traffeyere.com/peers/peer0.regulator.traffeyere.com/tls:/etc/hyperledger/fabric/tls
      - /var/run:/host/var/run
    ports:
      - "9051:9051"
      - "9447:9447"
    networks:
      - traffeyere-blockchain
      - monitoring-network
    external_links:
      - couchdb0-regulator

  # ===========================================================================
  # BLOCKCHAIN API GATEWAY
  # ===========================================================================
  
  # API Gateway pour intégration avec la plateforme
  blockchain-api-gateway:
    build:
      context: ..
      dockerfile: ./core/blockchain-layer/api-gateway/Dockerfile
    container_name: traffeyere-blockchain-api
    restart: unless-stopped
    environment:
      # Configuration API
      API_PORT: 8090
      API_HOST: 0.0.0.0
      
      # Configuration Hyperledger Fabric
      HLF_NETWORK_NAME: traffeyere-network
      HLF_CHANNEL_NAME: datachannel
      HLF_CHAINCODE_NAME: waterquality
      
      # Organisation SAUR (par défaut)
      HLF_ORG_MSP_ID: SAURMSP
      HLF_ORG_NAME: saur
      HLF_PEER_ENDPOINT: grpcs://peer0.saur.traffeyere.com:7051
      HLF_ORDERER_ENDPOINT: grpcs://orderer0.traffeyere.com:7050
      
      # Certificats et clés
      HLF_MSP_PATH: /crypto/peerOrganizations/saur.traffeyere.com/users/Admin@saur.traffeyere.com/msp
      HLF_TLS_CERT_PATH: /crypto/peerOrganizations/saur.traffeyere.com/peers/peer0.saur.traffeyere.com/tls/ca.crt
      
      # Connexion Backend
      BACKEND_API_URL: http://backend:8000
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      
      # Redis pour cache blockchain
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/7
      
      # Configuration transactionnelle
      TRANSACTION_TIMEOUT: ${BLOCKCHAIN_TX_TIMEOUT:-30}
      QUERY_TIMEOUT: ${BLOCKCHAIN_QUERY_TIMEOUT:-10}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - blockchain_api_logs:/app/logs
      - ../blockchain-hyperledger/network-config/organizations:/crypto:ro
    ports:
      - "8090:8090"
    networks:
      - traffeyere-blockchain
      - backend
      - monitoring-network
    external_links:
      - peer0.saur.traffeyere.com
      - orderer0.traffeyere.com
      - redis
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  # Orderer volumes
  orderer0_data:
    driver: local
  orderer1_data:
    driver: local
  orderer2_data:
    driver: local
  
  # Peer volumes
  peer0_saur_data:
    driver: local
  peer0_regulator_data:
    driver: local
  
  # CouchDB volumes
  couchdb0_saur_data:
    driver: local
  couchdb0_regulator_data:
    driver: local
  
  # API Gateway
  blockchain_api_logs:
    driver: local

networks:
  traffeyere-blockchain:
    name: traffeyere-blockchain
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
  backend:
    name: traffeyere-backend
    external: true
  monitoring-network:
    name: traffeyere-monitoring
    external: true