# Configuration SOC IA-Powered
# Station Traffeyère - RNCP 39394 Semaine 6

siem:
  ml_model: "IsolationForest"
  contamination: 0.1
  training_samples: 1000
  confidence_threshold: 0.8
  database_path: "data/soc_database.db"

soar:
  max_execution_time: 300  # 5 minutes
  automation_level: "full"  # full, partial, manual
  playbooks_enabled:
    - "critical_malware_response"
    - "network_intrusion_response" 
    - "data_exfiltration_response"
    - "iot_device_compromise"
    - "supply_chain_attack"

threat_intel:
  update_interval: 3600  # 1 heure
  database_path: "data/threat_intelligence.db"
  feeds:
    anssi_cert_fr:
      enabled: true
      classification: "TLP:WHITE"
      url: "https://www.cert.ssi.gouv.fr/feeds/"
    misp_local:
      enabled: true
      classification: "TLP:AMBER"
      url: "http://localhost:8080/events/restSearch"
      api_key: "demo-api-key-misp-2024"
    virustotal:
      enabled: true
      classification: "TLP:GREEN"
      url: "https://www.virustotal.com/vtapi/v2/"
      api_key: "demo-vt-api-key"

dashboard:
  host: "0.0.0.0"
  port: 8000
  refresh_interval: 5  # secondes
  max_incidents_display: 50

performance:
  target_mttr_minutes: 11.3  # RNCP 39394 requirement
  compliance_threshold: 80   # % minimum
  
logging:
  level: "INFO"
  file: "logs/soc.log"
  max_size_mb: 100
  backup_count: 5
