apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus  
    access: proxy
    url: http://host.docker.internal:9090
    uid: prometheus-main
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      incrementalQuerying: true
